version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    container_name: ecommerce_postgres

volumes:
  postgres: